# Generated by Django 4.0.1 on 2023-03-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='start_time',
            new_name='start',
        ),
    ]
